<a href="https://colab.research.google.com/github/morczyko/data-science-bootcamp/blob/main/01_wprowadzenie/01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [1]:
import numpy as np

np.__version__

'1.22.4'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

1D Array

In [4]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [6]:
x.ndim

1

In [7]:
x.shape

(3,)

In [8]:
x.size

3

In [9]:
x.dtype

dtype('int64')

In [10]:
print(x)

[1 2 3]


2D Array

In [11]:
y = np.array([[2, 3, 4], [-3, -4, -5]])
print(y)

[[ 2  3  4]
 [-3 -4 -5]]


In [13]:
y.shape

(2, 3)

In [14]:
y.ndim

2

3D Array

In [15]:
np.zeros(shape=(10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones(shape=(5,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [17]:
np.full(shape=(3,4), fill_value=4, dtype='int')

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [18]:
np.arange(start=50, stop=100, step=10)

array([50, 60, 70, 80, 90])

In [21]:
np.arange(start=1, stop=0, step=-0.05)

array([1.  , 0.95, 0.9 , 0.85, 0.8 , 0.75, 0.7 , 0.65, 0.6 , 0.55, 0.5 ,
       0.45, 0.4 , 0.35, 0.3 , 0.25, 0.2 , 0.15, 0.1 , 0.05])

In [23]:
a = np.arange(15)
a.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [24]:
a.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [26]:
a.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [28]:
x = np.array([[1, 3], [-2,4]])
y = np.array([[2,4], [6,8]])
print(x, '\n')
print(y)

[[ 1  3]
 [-2  4]] 

[[2 4]
 [6 8]]


In [29]:
x * y

array([[  2,  12],
       [-12,  32]])

In [30]:
np.dot(x,y)

array([[20, 28],
       [20, 24]])

In [31]:
np.random.seed(0)

np.random.randn()

1.764052345967664

In [32]:
np.random.randn(10,4)

array([[ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799],
       [-0.97727788,  0.95008842, -0.15135721, -0.10321885],
       [ 0.4105985 ,  0.14404357,  1.45427351,  0.76103773],
       [ 0.12167502,  0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574, -2.55298982],
       [ 0.6536186 ,  0.8644362 , -0.74216502,  2.26975462],
       [-1.45436567,  0.04575852, -0.18718385,  1.53277921],
       [ 1.46935877,  0.15494743,  0.37816252, -0.88778575],
       [-1.98079647, -0.34791215,  0.15634897,  1.23029068],
       [ 1.20237985, -0.38732682, -0.30230275, -1.04855297]])

In [33]:
np.random.rand()

0.5701967704178796

In [34]:
np.random.randint(low=10, high=100)

94

In [35]:
np.random.randint(low=10, high=100, size=10)

array([85, 78, 16, 78, 57, 13, 86, 62, 88, 25])

In [37]:
np.random.choice([1,2,5,7])

7

In [44]:
a = np.random.randn(5)
a

array([ 1.54371643, -0.40211489,  0.8647491 , -0.22686923,  0.81116027])

In [42]:
np.argmax(a)

2

In [43]:
a[np.argmin(a)]

-1.1230571153785116

In [46]:
np.argsort(a)

array([1, 3, 4, 2, 0])

In [47]:
np.mean(a)

0.5181283371287042

In [48]:
b = np.arange(20)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [49]:
b[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [50]:
b[:5]

array([0, 1, 2, 3, 4])

In [53]:
b[-1:1]

array([], dtype=int64)

In [55]:
b[-1::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [57]:
b = b.reshape(4,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [58]:
b[1]

array([5, 6, 7, 8, 9])

In [64]:
b[1:3,2:4]

array([[ 7,  8],
       [12, 13]])

In [65]:
b[:,2:5]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [67]:
b[1,2] = 14
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [68]:
for row in b:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [70]:
for row in b:
  print(row[2:])

[2 3 4]
[14  8  9]
[12 13 14]
[17 18 19]


In [71]:
b.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [72]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [73]:
b.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [78]:
c = np.arange(-10, 10, 0.5)
c = c.reshape(10, -1)
c

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [79]:
c > 5

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [80]:
c[c > 5]

array([5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])