<a href="https://colab.research.google.com/github/morczyko/data-science-bootcamp/blob/main/01_wprowadzenie/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [5]:
v1 = np.array([-1, 4])

np.linalg.norm(v1)

4.123105625617661

In [7]:
v2 = np.array([-10,10,10])
np.linalg.norm(v2)

17.320508075688775

In [8]:
p = np.array([1, 5])
q= np.array([2,-7])

print(p-q)

[-1 12]


In [9]:
np.linalg.norm(p-q)

12.041594578792296

In [10]:
p = np.array([1, 5,23])
q = np.array([2,-7,-45])

print(p-q)

[-1 12 68]


In [11]:
np.linalg.norm(p-q)

69.05794668247819

In [15]:
a = np.array([[1,2], [5,3]])

np.linalg.det(a)

-6.999999999999999

In [16]:
np.trace(a)

4

In [17]:
print(a)

[[1 2]
 [5 3]]


In [18]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
b = np.array([[1], [-1]])

z = np.dot(a, b)
z

array([[-1],
       [ 2]])

In [21]:
z.shape

(2, 1)

In [22]:
a = np.array([[1,3,9],[5,7,5],[7,19,23]])
np.linalg.det(a)

239.99999999999997

In [23]:
np.trace(a)

31

In [24]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [27]:
b = np.linalg.inv(a)
b

array([[ 0.275     ,  0.425     , -0.2       ],
       [-0.33333333, -0.16666667,  0.16666667],
       [ 0.19166667,  0.00833333, -0.03333333]])

In [30]:
np.set_printoptions(precision=4, suppress=True)

print(np.dot(a,b), '\n')

print(np.dot(b,a))

[[ 1. -0.  0.]
 [-0.  1. -0.]
 [-0. -0.  1.]] 

[[ 1. -0. -0.]
 [-0.  1.  0.]
 [ 0.  0.  1.]]


In [31]:
a.T

array([[ 1,  5,  7],
       [ 3,  7, 19],
       [ 9,  5, 23]])

In [32]:
b.T

array([[ 0.275 , -0.3333,  0.1917],
       [ 0.425 , -0.1667,  0.0083],
       [-0.2   ,  0.1667, -0.0333]])